name = "SearchAlgorithms"
version = "0.1.0"
defaultTargets = ["SearchAlgorithms"]

[[lean_lib]]
name = "SearchAlgorithms"

[[lean_lib]]
name = "BenchAux"

[[lean_exe]]
name = "bench"
root = "Bench"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.0"

[[lean_exe]]
name = "benchbroom"
root = "BenchBroom"

[[lean_exe]]
name = "benchhuge"
root = "BenchHuge"

[[lean_exe]]
name = "benchheap"
root = "BenchHeap"
[[lean_exe]]
name = "benchlazy"
root = "BenchHeapLazy"

[[lean_exe]]
name = "benchpath"
root = "BenchPath"

[[lean_exe]]
name = "benchcache"
root = "BenchCache"

[[lean_exe]]
name = "benchmemo"
root = "BenchMemo"
